module.exports = {
  'array': '数组',
  'backtracking': '回溯法',
  'binary-search': '二分搜索',
  'bit-manipulation': '位操作',
  'depth-first-search': '深度优先搜索',
  'divide-and-conquer': '分治法',
  'dynamic-programming': '动态规划',
  'greedy': '贪心',
  'hash-table': '哈希表',
  'heap': '堆',
  'linked-list': '链表',
  'math': '数学',
  'queue': '队列',
  'stack': '栈',
  'string': '字符串',
  'tree': '树',
  'two-pointers': '双指针',
};